
services:
###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "80"
###< symfony/mercure-bundle ###

###> doctrine/mongodb-odm-bundle ###
  mongodb:
    ports:
      - "27017"
###< doctrine/mongodb-odm-bundle ###
