services:
    rabbitmq:
        image: ${COMPOSE_PROJECT_NAME}-rabbitmq
        build:
            context: ./docker/rabbitmq/
            dockerfile: ./Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
        hostname: rabbitmq
        restart: always
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
            RABBITMQ_DEFAULT_VHOST: /
        ports:
            - "${RABBITMQ_MANAGEMENT_PORT}:15672"
        volumes:
            - ./var/rabbitmq:/var/lib/rabbitmq:delegated
        networks:
            - symfony

    elasticsearch:
        image: ${COMPOSE_PROJECT_NAME}-elasticsearch
        build:
            context: ./docker/
            args:
                ELK_VERSION: ${ELK_VERSION}
            dockerfile: ./elasticsearch/Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}-elasticsearch
        restart: always
        environment:
            ES_JAVA_OPTS: "-Xmx4096m -Xms4096m"
            ELASTIC_USERNAME: ${ELASTICSEARCH_USERNAME}
            ELASTIC_PASSWORD: ${ELASTICSEARCH_PASSWORD}
            # Use single node discovery in order to disable production mode and avoid bootstrap checks
            # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
            discovery.type: single-node
        ports:
            - "${ELASTIC_HTTP_PORT}:9200"
            - "${ELASTIC_TRANSPORT_PORT}:9300"
        volumes:
            - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - ./var/elasticsearch-data:/usr/share/elasticsearch/data:delegated
        networks:
            - symfony

    kibana:
        image: ${COMPOSE_PROJECT_NAME}-kibana
        platform: linux/x86_64
        build:
            context: ./docker/
            args:
                ELK_VERSION: ${ELK_VERSION}
            dockerfile: ./kibana/Dockerfile
        container_name: ${COMPOSE_PROJECT_NAME}-kibana
        ports:
            - "${KIBANA_PORT}:5601"
        volumes:
            - ./docker/prod/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
        depends_on:
            - elasticsearch
        networks:
            - symfony

    redis:
        image: ${COMPOSE_PROJECT_NAME}-redis
        container_name: ${COMPOSE_PROJECT_NAME}-redis
        build:
            context: ./docker/redis
        restart: always
        volumes:
            - ./var/redis:/data:delegated
        networks:
            - symfony

networks:
    symfony:
        name: symfony
